require: rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
  NewCops: enable

inherit_mode:
  merge:
    - Exclude

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false
